DEBUG = True
SECRET_KEY = 'lalalalalalala'

SENTRY_DSN = ""

SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False

CACHE_TYPE = "simple"
CACHE_KEY_PREFIX = "colombia::"

DEBUG_TB_ENABLED = DEBUG
PROFILE = False
PORT = 8001

# Ingestion settings
DATASET_ROOT = "/nfs/projects_nobackup/c/cidgrowlab/Atlas/Colombia/beta/"
YEAR_MIN_TRADE = 2007
YEAR_MAX_TRADE = 2014
YEAR_MIN_INDUSTRY = 2007
YEAR_MAX_INDUSTRY = 2014
YEAR_MIN_DEMOGRAPHIC = 2007
YEAR_MAX_DEMOGRAPHIC = 2014
